#!/bin/sh
# Auto-generated display configuration for Hyprland
# Generated by Kolibri Settings

hyprctl keyword monitor eDP-1,1920x1080@60.01,3840x0,1.00
hyprctl keyword monitor DP-5,1920x1080@60.00,1920x0,1.00
hyprctl keyword monitor DP-6,1920x1080@60.00,0x0,1.00
