#!/bin/sh
# Auto-generated display configuration for Hyprland
# Generated by Kolibri Settings

hyprctl keyword monitor eDP-1,1920x1080@60.01,0x0,1.00
hyprctl keyword monitor HDMI-A-1,3840x2160@30.00,1920x0,1.00,mirror,eDP-1
