[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#653e00'

[colors.cursor]
text = '#131313'
cursor = '#ffb960'

[colors.normal]
black   = '#131313'
red     = '#ff5b50'
green   = '#79ff60'
yellow  = '#ffe150'
blue    = '#f2a23c'
magenta = '#764200'
cyan    = '#ffb960'
white   = '#fff6eb'

[colors.bright]
black   = '#a59e96'
red     = '#ff8f87'
green   = '#a1ff8f'
yellow  = '#ffeb8f'
blue    = '#ffc377'
magenta = '#ffcd8f'
cyan    = '#ffdfb7'
white   = '#fffbf7'
