[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.selection]
text = '#e2e2e2'
background = '#534600'

[colors.cursor]
text = '#131313'
cursor = '#e0c64c'

[colors.normal]
black   = '#131313'
red     = '#ff5845'
green   = '#60e04c'
yellow  = '#ffe145'
blue    = '#d4b72c'
magenta = '#675500'
cyan    = '#e0c64c'
white   = '#ebe7d8'

[colors.bright]
black   = '#918f83'
red     = '#ff8d80'
green   = '#99ff89'
yellow  = '#ffec89'
blue    = '#f6de6c'
magenta = '#ffea89'
cyan    = '#fff1b3'
white   = '#fffdf6'
