[colors.primary]
background = '#19120d'
foreground = '#f0dfd7'

[colors.selection]
text = '#f0dfd7'
background = '#6e380f'

[colors.cursor]
text = '#19120d'
cursor = '#ffb689'

[colors.normal]
black   = '#19120d'
red     = '#ff7972'
green   = '#96ff7f'
yellow  = '#ffe572'
blue    = '#f29f6b'
magenta = '#763811'
cyan    = '#ffb689'
white   = '#fff5ef'

[colors.bright]
black   = '#a59e99'
red     = '#ffa39f'
green   = '#b5ffa5'
yellow  = '#ffefa5'
blue    = '#ffc09a'
magenta = '#ffcbac'
cyan    = '#ffdec9'
white   = '#fffbf8'
