[colors.primary]
background = '#252018'
foreground = '#f3f2f2'

[colors.cursor]
text = '#252018'
cursor = '#f3f2f2'

[colors.vi_mode_cursor]
text = '#252018'
cursor = '#e4af67'

[colors.search.matches]
foreground = '#322a20'
background = '#91cc66'

[colors.search.focused_match]
foreground = '#322a20'
background = '#e4af67'

[colors.footer_bar]
foreground = '#322a20'
background = '#e8e6e3'

[colors.hints.start]
foreground = '#322a20'
background = '#cfd65c'

[colors.hints.end]
foreground = '#322a20'
background = '#cfd65c'

[colors.selection]
text = '#b6b3af'
background = '#322a20'


[colors.normal]
black   = '#322a20'
red     = '#fd4663'
green   = '#e4af67'
yellow  = '#cfd65c'
blue    = '#91cc66'
magenta = '#ecc693'
cyan    = '#e4e996'
white   = '#f3f2f2'


[colors.bright]
black   = '#706a60'
red     = '#fd4663'
green   = '#e4af67'
yellow  = '#cfd65c'
blue    = '#91cc66'
magenta = '#ecc693'
cyan    = '#e4e996'
white   = '#f3f2f2'


[colors.dim]
black   = '#322a20'
red     = '#fd4663'
green   = '#e4af67'
yellow  = '#cfd65c'
blue    = '#91cc66'
magenta = '#ecc693'
cyan    = '#e4e996'
white   = '#f3f2f2'
